# Generated by Django 2.1.2 on 2018-10-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
