# Generated by Django 2.1.1 on 2018-09-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
