# Generated by Django 2.1.1 on 2018-09-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='account',
            name='street_address',
        ),
        migrations.AddField(
            model_name='account',
            name='street_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='street_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='unit_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='part_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
