# Generated by Django 2.1.1 on 2018-09-12 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='hashed_security_answer',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='security_question',
        ),
    ]
