# Generated by Django 2.1.1 on 2018-09-11 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_account_account_note_client_job_contractor_job_job_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Account')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Job')),
            ],
        ),
        migrations.DeleteModel(
            name='Client_Job',
        ),
    ]
