# Generated by Django 2.1.1 on 2018-09-21 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20180921_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Job'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Job'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Note'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Part'),
        ),
    ]
