# Generated by Django 2.1.1 on 2018-09-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20180921_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='part',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
