# Generated by Django 2.1.1 on 2018-09-21 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20180921_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='contractor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='server.Contractor'),
            preserve_default=False,
        ),
    ]
